import { expect, test } from "@jest/globals";
import {
  EMPTY_CELL,
  FILLED_CELL,
  HORIZONTAL,
  VERTICAL,
} from "./GameBoardFactoryUtil";
import ShipFactory from "../ShipFactory/ShipFactory";
import GameBoardFactory from "./GameBoardFactory";

test("initial board state :  no ship", () => {
  const tmpGameBoard = GameBoardFactory();

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("ship placed at given coordinates Valid :  horizontal", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ row: 0, col: 0, orientation: HORIZONTAL }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("ship placed at given coordinates Valid :  vertical", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ row: 0, col: 0, orientation: VERTICAL }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: FILLED_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: FILLED_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: FILLED_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: FILLED_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("Ships placed at given coordinates inValid : horizontal", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ row: 9, col: 9, orientation: HORIZONTAL }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("Ships placed at given coordinates inValid : vertical", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ row: 9, col: 9, orientation: VERTICAL }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("ships dont overlap", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip1 = ShipFactory(4);
  const tmpShip2 = ShipFactory(4);

  tmpGameBoard.placeShip({ row: 0, col: 0, orientation: HORIZONTAL }, tmpShip1);
  tmpGameBoard.placeShip({ row: 0, col: 0, orientation: VERTICAL }, tmpShip2);
  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("receive Attack on ship", () => {
  const tmpGameBoard = GameBoardFactory();

  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ row: 0, col: 0, orientatio: HORIZONTAL }, tmpShip);

  tmpGameBoard.receiveAttack({ row: 0, col: 0 });

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: FILLED_CELL, isHit: true },
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: FILLED_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("receive Attack on empty place", () => {
  const tmpGameBoard = GameBoardFactory();

  tmpGameBoard.receiveAttack({ row: 0, col: 0 });

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: EMPTY_CELL, isHit: true },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);
});

test("fullShip Sunk : {check lives system}", () => {
  const tmpGameBoard = GameBoardFactory();

  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ row: 0, col: 0, orientatio: HORIZONTAL }, tmpShip);

  expect(tmpGameBoard.livesLeft).toBe(1);

  tmpGameBoard.receiveAttack({ x: 0, y: 0 });
  tmpGameBoard.receiveAttack({ x: 1, y: 0 });
  tmpGameBoard.receiveAttack({ x: 2, y: 0 });
  tmpGameBoard.receiveAttack({ x: 3, y: 0 });

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: FILLED_CELL, isHit: true },
      { type: FILLED_CELL, isHit: true },
      { type: FILLED_CELL, isHit: true },
      { type: FILLED_CELL, isHit: true },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
    [
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
      { type: EMPTY_CELL, isHit: false },
    ],
  ]);

  expect(tmpGameBoard.livesLeft).toBe(0);
  expect(tmpGameBoard.gameOver).toBe(true);
});
