import { expect, test } from "@jest/globals";
import GameBoardFactory from "./GameBoardFactory";
import ShipFactory from "../ShipFactory/ShipFactory";

test.only("initial board state :  no ship", () => {
  const tmpGameBoard = GameBoardFactory();

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("ship placed at given coordinates Valid :  horizontal", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ x: 0, y: 0, orientation: "hor" }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("ship placed at given coordinates Valid :  vertical", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ x: 0, y: 0, orientation: "ver" }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "ship", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "ship", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "ship", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "ship", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("Ships placed at given coordinates inValid : horizontal", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ x: 9, y: 9, orientation: "hor" }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("Ships placed at given coordinates inValid : vertical", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ x: 9, y: 9, orientation: "ver" }, tmpShip);

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("ships dont overlap", () => {
  const tmpGameBoard = GameBoardFactory();
  const tmpShip1 = ShipFactory(4);
  const tmpShip2 = ShipFactory(4);

  tmpGameBoard.placeShip({ x: 0, y: 0, orientation: "hor" }, tmpShip1);
  tmpGameBoard.placeShip({ x: 0, y: 0, orientation: "ver" }, tmpShip2);
  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("receive Attack on ship", () => {
  const tmpGameBoard = GameBoardFactory();

  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ x: 0, Y: 0, orientatio: "hor" }, tmpShip);

  tmpGameBoard.receiveAttack({ x: 0, y: 0 });

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "ship", isHit: true },
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "ship", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("receive Attack on empty place", () => {
  const tmpGameBoard = GameBoardFactory();

  tmpGameBoard.receiveAttack({ x: 0, y: 0 });

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "empty", isHit: true },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);
});

test("fullShip Sunk : {check lives system}", () => {
  const tmpGameBoard = GameBoardFactory();

  const tmpShip = ShipFactory(4);

  tmpGameBoard.placeShip({ x: 0, Y: 0, orientatio: "hor" }, tmpShip);

  expect(tmpGameBoard.livesLeft).toBe(1);

  tmpGameBoard.receiveAttack({ x: 0, y: 0 });
  tmpGameBoard.receiveAttack({ x: 1, y: 0 });
  tmpGameBoard.receiveAttack({ x: 2, y: 0 });
  tmpGameBoard.receiveAttack({ x: 3, y: 0 });

  expect(tmpGameBoard.gridStatus).toMatchObject([
    [
      { type: "ship", isHit: true },
      { type: "ship", isHit: true },
      { type: "ship", isHit: true },
      { type: "ship", isHit: true },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
    [
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
      { type: "empty", isHit: false },
    ],
  ]);

  expect(tmpGameBoard.livesLeft).toBe(0);
  expect(tmpGameBoard.gameOver).toBe(true);
});
